/* Generated by Babel */
// VSL Wrapper
// VSL Interface & Controls

"use strict";

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj["default"] = obj; return newObj; } }

var _exprExpr = require("expr/expr");

var _ENGINE_EXPRESSION = _interopRequireWildcard(_exprExpr);

var VSL = {};