/* Generated by Babel */
// Explicit type literals
'use strict';

Object.defineProperty(exports, '__esModule', {
    value: true
});

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ('value' in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

var _get = function get(_x, _x2, _x3) { var _again = true; _function: while (_again) { var object = _x, property = _x2, receiver = _x3; desc = parent = getter = undefined; _again = false; if (object === null) object = Function.prototype; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x = parent; _x2 = property; _x3 = receiver; _again = true; continue _function; } } else if ('value' in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj['default'] = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

function _inherits(subClass, superClass) { if (typeof superClass !== 'function' && superClass !== null) { throw new TypeError('Super expression must either be null or a function, not ' + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var _tokParser = require('../tok/parser');

var _tokParser2 = _interopRequireDefault(_tokParser);

var _tokLex = require('../tok/lex');

var _tokLex2 = _interopRequireDefault(_tokLex);

var _types = require('./types');

var Literal = _interopRequireWildcard(_types);

var CheddarAnyLiteral = (function (_CheddarLexer) {
    _inherits(CheddarAnyLiteral, _CheddarLexer);

    function CheddarAnyLiteral() {
        _classCallCheck(this, CheddarAnyLiteral);

        _get(Object.getPrototypeOf(CheddarAnyLiteral.prototype), 'constructor', this).apply(this, arguments);
    }

    _createClass(CheddarAnyLiteral, [{
        key: 'exec',

        // <Literal.Token><WHITE>:<WHITE><Literal.-Token>
        value: function exec() {
            var Parser = new _tokParser2['default'](this.Code, this.Index);

            Parser.parse(Literal.Token);
            Parser.jumpwhite();
            Parser.jumpliteral(':');
            Parser.jumpwhite();
            Parser.parse(Literal.String);

            return Parser;
        }
    }]);

    return CheddarAnyLiteral;
})(_tokLex2['default']);

exports['default'] = CheddarAnyLiteral;
module.exports = exports['default'];