/* Generated by Babel */
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

var _literalsString = require('../literals/string');

var _literalsString2 = _interopRequireDefault(_literalsString);

var _literalsLiteral = require('../literals/literal');

var _literalsLiteral2 = _interopRequireDefault(_literalsLiteral);

var String = _literalsString2['default'];
exports.String = String;
var Token = _literalsLiteral2['default'];
exports.Token = Token;