/* Generated by Babel */
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var CheddarType = function CheddarType(InternelRepresentation) {
    _classCallCheck(this, CheddarType);

    this.InternelRepresentation = InternelRepresentation;
};

exports["default"] = CheddarType;
module.exports = exports["default"];