#!/usr/bin/env sh

base=`dirname "$0"`
rel="$base/cheddar.js"
cpath="$(dirname $(readlink -f $0))"
CHEDDAR_EXE=$([[ -f "$rel" ]] && echo "$rel" || echo "$cpath/../share/cheddar/dist/cli/cheddar.js")
NODE_EXE=`which node`
"$NODE_EXE" "$CHEDDAR_EXE" "$@"