/* Generated by Babel */
/*
 * DEFAULT ERROR CODES
 * Codes:
  0. Success
  1. Unexpected token
  2. Unexpected 
**/

'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var SUCCESS = Symbol('er_SUCCESS');
exports.SUCCESS = SUCCESS;
var EXIT_NOTFOUND = Symbol('er_EXIT_NOTFOUND');
exports.EXIT_NOTFOUND = EXIT_NOTFOUND;
var UNEXPECTED_TOKEN = Symbol('er_UNEXPECTED_TOKEN');
exports.UNEXPECTED_TOKEN = UNEXPECTED_TOKEN;