/* Generated by Babel */
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var VSLType = function VSLType(InternelRepresentation) {
    _classCallCheck(this, VSLType);

    this.InternelRepresentation = InternelRepresentation;
};

exports["default"] = VSLType;
module.exports = exports["default"];