#!/usr/bin/env bash
echo "Downloading..."
npm install
echo "Installing..."
cpath="$(dirname $(readlink -f $0))"
$cpath/../node_modules/.bin/grunt install \
    --method=alias --rc=`bash < "$cpath/locrc"`