/* Generated by Babel */
// Tokenizer Class
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

require('VSLTokens');

var VSLTok = (function () {
    function VSLTok() {
        var Code = arguments.length <= 0 || arguments[0] === undefined ? "" : arguments[0];
        var Index = arguments.length <= 1 || arguments[1] === undefined ? 0 : arguments[1];

        _classCallCheck(this, VSLTok);

        this.Code = Code; // Tokenize given code
        this.Index = Index; // Tokenize given code at given index
        this.Tokens = new VSLTokens(null); // Result for Tokenized
    }

    _createClass(VSLTok, [{
        key: "Tokens",
        set: function set(v) {
            if (v instanceof VSLTokens) this.Tokens = v;else throw new TypeError("VSLTok: provided update `Tokens` is invalid");
        }
    }]);

    return VSLTok;
})();

exports["default"] = VSLTok;
module.exports = exports["default"];